### ISSUE TITLE
Split some caom2-search-server packages into a new library

### ISSUE THREAD

**Issue by jburke-cadc** [opencadc/caom2ui#50]
Some of the packages in caom2-search-server could be moved into a separate library for use by other web applications.  For example the ca.nrc.cadc.astro utilities, and the ca.nr.cadc.search.[parser|upload] packages. Possibly others.

Currently the caom2-search-server jar includes resources such as jsp, css, javascript, and image files specific to the caom2-search-server that other web applications would not want deployed into their web app.

**Comment by at88mph** [comment]
This was merged.  Closing.
